name: PrivateMine
version: '${project.version}'
main: skyblock.main.Main
api-version: 1.19
softdepend: [WorldEdit]
depend:
  - PlayerNPC
  - WorldGuard
commands:
  mine:
  pmine:
  pass:
  battlepass:
  rewards:
  gifts: